apiVersion: v1
kind: Namespace
metadata:
  name: kube-hunter
  labels:
    name: kube-hunter
---
# default deny all
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: kube-hunter
spec:
  podSelector: {}
  policyTypes:
    - Ingress