apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: rbac-restrict-cluster-admin
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: restrict-cluster-admin-binding
    match:
      resources:
        kinds: ["ClusterRoleBinding"]
    exclude:
      resources:
        names: ["kubeadm:*","minikube-rbac","kubernetes-dashboard","system:*"]
        selector:
          matchLabels:
            kyverno-policy-exempt: "true"
    validate:
      message: "El rol cluster-admin sólo puede asignarse al grupo platform-admins."
      deny:
        conditions:
          all:
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: "cluster-admin"
          - key: "{{ request.object.subjects[?kind=='Group'].name | contains(@, 'platform-admins') }}"
            operator: Equals
            value: false
