apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-secret-wildcards
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: audit-secret-wildcards
    match:
      resources:
        kinds:
        - ClusterRole
        - Role
    validate:
      message: "No debe usarse wildcard (*) en Secret o en sus verbs."
      pattern:
        rules:
        - resources:
          - "?(!['*'])"
          verbs:
          - "?(!['*'])"
