apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-secret-wildcards
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: audit-secret-wildcards
    match:
      any:
      - resources:
          kinds:
          - ClusterRole
          - Role
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kyverno
          - ingress-nginx
          - kube-public
          - kube-node-lease
          - kubernetes-dashboard
          - default
    validate:
      message: "No use comodines (*) en resources o verbs de Roles/ClusterRoles."
      foreach:
      - list: rules
        elementScope: true
        deny:
          conditions:
            any:
            - key: "{{ element.resources | contains(@, '*') }}"
              operator: Equals
              value: "true"
            - key: "{{ element.verbs | contains(@, '*') }}"
              operator: Equals
              value: "true"
